name: Run BDD Tests and Generate Allure Report

on:
  push:
    branches: [ main, master ] # Trigger on pushes to main or master
  pull_request:
    branches: [ main, master ] # Trigger on pull requests to main or master

jobs:
  behave-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Use latest version

    - name: Set up Python
      uses: actions/setup-python@v5 # Use latest version
      with:
        python-version: '3.10' # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Behave Tests with Allure
      run: |
        behave -f allure_behave.formatter:AllureFormatter -o allure-results features/
      # Continue even if tests fail, so report is always uploaded
      continue-on-error: true 

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4 # Use latest version
      if: always() # Always upload artifacts, even if tests fail
      with:
        name: allure-results-loyalty-program
        path: allure-results/
        retention-days: 7 # Keep artifacts for 7 days
